const DASHBOARD_HOME = '/dashboard';
const DASHBOARD_DETAIL = '/dashboard/detail';
const DASHBOARD_LOGIN = '/';
const DASHBOARD_FORGOT = '/forgot';
const DASHBOARD_HELLO = '/dashboard/hello';
const DASHBOARD_TABLE = '/dashboard/table';

const PRIVATE_ROUTES = [
	DASHBOARD_HOME,
	DASHBOARD_DETAIL,
	DASHBOARD_HELLO,
	DASHBOARD_TABLE,
];
const AUTH_ROUTES = [DASHBOARD_LOGIN, DASHBOARD_FORGOT];

export {
	DASHBOARD_HOME,
	DASHBOARD_LOGIN,
	DASHBOARD_DETAIL,
	PRIVATE_ROUTES,
	AUTH_ROUTES,
	DASHBOARD_HELLO,
	DASHBOARD_TABLE,
};
